#!/bin/bash
# Build and package pvr.kofin for Linux and/or Android
#
# Usage:
#   ./scripts/package.sh              # build + package both platforms
#   ./scripts/package.sh linux        # Linux only
#   ./scripts/package.sh android      # Android only
#
# Output zips go to /media/bluecon/docs/IT/kofin/builds/
# Naming convention:
#   pvr.kofin-{version}-linux-x86_64-kodi21.zip
#   pvr.kofin-{version}-android-armeabi-v7a-kodi22.zip

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BUILDS_DIR="/media/bluecon/docs/IT/kofin/builds"
KOFIN_BASE="/media/bluecon/docs/IT/kofin"

# Android toolchain paths
NDK_DIR="$KOFIN_BASE/android-ndk-r25c"
KODI_PIERS_INCLUDE="$KOFIN_BASE/kodi-piers/xbmc/addons/kodi-dev-kit/include"
ANDROID_DEPS="$KOFIN_BASE/android-deps"
STRIP="$NDK_DIR/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[ OK ]${NC} $1"; }
fail()    { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

get_version() {
  if [ -f "$PROJECT_DIR/VERSION" ]; then
    cat "$PROJECT_DIR/VERSION" | tr -d '[:space:]'
  else
    echo "0.1.0"
  fi
}

# Common files to include in every zip
stage_resources() {
  local staging="$1"
  mkdir -p "$staging/resources/scripts" \
           "$staging/resources/language/resource.language.en_gb" \
           "$staging/resources/data"

  cp "$PROJECT_DIR/pvr.kofin/resources/settings.xml" "$staging/resources/"
  cp "$PROJECT_DIR/pvr.kofin/resources/scripts/trigger.py" "$staging/resources/scripts/"
  cp "$PROJECT_DIR/pvr.kofin/resources/language/resource.language.en_gb/strings.po" \
     "$staging/resources/language/resource.language.en_gb/"
  cp -r "$PROJECT_DIR/pvr.kofin/resources/data/"* "$staging/resources/data/" 2>/dev/null || true
  [ -f "$PROJECT_DIR/pvr.kofin/icon.png" ] && cp "$PROJECT_DIR/pvr.kofin/icon.png" "$staging/"
}

build_linux() {
  local version="$1"
  local build_dir="$PROJECT_DIR/build"

  info "Building Linux x86_64 (Kodi v21)..."
  mkdir -p "$build_dir"
  cd "$build_dir"
  cmake "$PROJECT_DIR" -DCMAKE_BUILD_TYPE=Release
  cmake --build . --config Release -j"$(nproc)"

  local so_file="$build_dir/pvr.kofin.so.$version"
  [ -f "$so_file" ] || fail "Linux build output not found: $so_file"
  success "Linux build complete"
}

package_linux() {
  local version="$1"
  local build_dir="$PROJECT_DIR/build"
  local staging="/tmp/pvr.kofin-staging-linux/pvr.kofin"
  local zipname="pvr.kofin-${version}-linux-x86_64-kodi21.zip"

  info "Packaging $zipname..."
  rm -rf /tmp/pvr.kofin-staging-linux
  mkdir -p "$staging"

  # addon.xml (generated by Kodi build system)
  cp "$build_dir/pvr.kofin/addon.xml" "$staging/"

  # Versioned .so (matches library_linux= in addon.xml)
  cp "$build_dir/pvr.kofin.so.$version" "$staging/"

  stage_resources "$staging"

  rm -f "$BUILDS_DIR/$zipname"
  cd /tmp/pvr.kofin-staging-linux
  zip -r "$BUILDS_DIR/$zipname" pvr.kofin/
  rm -rf /tmp/pvr.kofin-staging-linux

  success "$zipname ($(du -h "$BUILDS_DIR/$zipname" | cut -f1))"
}

build_android() {
  local version="$1"
  local build_dir="$PROJECT_DIR/build-android"

  [ -d "$NDK_DIR" ] || fail "Android NDK not found at $NDK_DIR"
  [ -d "$KODI_PIERS_INCLUDE" ] || fail "Kodi Piers headers not found at $KODI_PIERS_INCLUDE"

  info "Building Android armeabi-v7a (Kodi v22)..."
  mkdir -p "$build_dir"
  cd "$build_dir"
  cmake "$PROJECT_DIR" \
    -DCMAKE_TOOLCHAIN_FILE="$NDK_DIR/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI=armeabi-v7a \
    -DANDROID_PLATFORM=android-21 \
    -DCMAKE_BUILD_TYPE=Release \
    -DKODI_INCLUDE_DIR="$KODI_PIERS_INCLUDE" \
    -DJSONCPP_ROOT="$ANDROID_DEPS" \
    -DCMAKE_PREFIX_PATH="$ANDROID_DEPS"
  cmake --build . --config Release -j"$(nproc)"

  [ -f "$build_dir/pvr.kofin.so" ] || fail "Android build output not found"
  success "Android build complete"
}

package_android() {
  local version="$1"
  local build_dir="$PROJECT_DIR/build-android"
  local staging="/tmp/pvr.kofin-staging-android/pvr.kofin"
  local zipname="pvr.kofin-${version}-android-armeabi-v7a-kodi22.zip"

  info "Packaging $zipname..."
  rm -rf /tmp/pvr.kofin-staging-android
  mkdir -p "$staging"

  # addon.xml (generated by CMake standalone mode from Kodi v22 headers)
  cp "$build_dir/pvr.kofin/addon.xml" "$staging/"

  # Stripped .so
  "$STRIP" -o "$staging/pvr.kofin.so" "$build_dir/pvr.kofin.so"

  stage_resources "$staging"

  rm -f "$BUILDS_DIR/$zipname"
  cd /tmp/pvr.kofin-staging-android
  zip -r "$BUILDS_DIR/$zipname" pvr.kofin/
  rm -rf /tmp/pvr.kofin-staging-android

  success "$zipname ($(du -h "$BUILDS_DIR/$zipname" | cut -f1))"
}

# Main
main() {
  local target="${1:-all}"
  local version
  version=$(get_version)

  echo ""
  echo "========================================"
  echo "  pvr.kofin v${version} — Build & Package"
  echo "========================================"
  echo ""

  mkdir -p "$BUILDS_DIR"

  case "$target" in
    linux)
      build_linux "$version"
      package_linux "$version"
      ;;
    android)
      build_android "$version"
      package_android "$version"
      ;;
    all)
      build_linux "$version"
      package_linux "$version"
      build_android "$version"
      package_android "$version"
      ;;
    *)
      echo "Usage: $0 [linux|android|all]"
      exit 1
      ;;
  esac

  echo ""
  echo "Output:"
  ls -lh "$BUILDS_DIR"/pvr.kofin-${version}-*.zip 2>/dev/null
  echo ""
}

main "$@"
